/**
 * AETHER OS — Phase 9.10 AI Provider Adapter Layer
 * Milestone 4 Component: Message Contracts & Translation Types (`message-types.ts`)
 *
 * @file message-types.ts
 * @description Pure, immutable interface declarations representing canonical AETHER OS conversation messages,
 * contexts, tool calls, translation requests, and translation responses.
 *
 * @module @aether/provider-adapters/message-types
 * @version 1.0.0
 * @status FROZEN ARCHITECTURE SPECIFICATION — MILESTONE 4
 */

import type { ProviderUsageStatistics } from "./adapter-types";

/**
 * System prompt message instructing model behavior.
 */
export interface SystemMessage {
  readonly id: string;
  readonly role: "system";
  readonly content: string;
  readonly timestamp: number;
}

/**
 * User prompt message containing text or multimodal content items.
 */
export interface UserMessage {
  readonly id: string;
  readonly role: "user";
  readonly content: string | ReadonlyArray<Readonly<Record<string, unknown>>>;
  readonly timestamp: number;
  readonly name?: string;
}

/**
 * Tool/function call request descriptor invoked by an assistant message.
 */
export interface ToolCallDescriptor {
  readonly id: string;
  readonly type: "function";
  readonly name: string;
  readonly arguments: Readonly<Record<string, unknown>> | string;
}

/**
 * Assistant response message generated by model inference.
 */
export interface AssistantMessage {
  readonly id: string;
  readonly role: "assistant";
  readonly content?: string;
  readonly toolCalls?: ReadonlyArray<ToolCallDescriptor>;
  readonly reasoningContent?: string;
  readonly timestamp: number;
}

/**
 * Result message returned from executing a tool call.
 */
export interface ToolMessage {
  readonly id: string;
  readonly role: "tool";
  readonly toolCallId: string;
  readonly name: string;
  readonly content: string;
  readonly timestamp: number;
}

/**
 * Discriminated union of all valid conversation message types.
 */
export type ConversationMessage = SystemMessage | UserMessage | AssistantMessage | ToolMessage;

/**
 * Canonical context container holding conversation history and session metadata.
 */
export interface ConversationContext {
  readonly conversationId: string;
  readonly messages: ReadonlyArray<ConversationMessage>;
  readonly metadata?: Readonly<Record<string, unknown>>;
}

/**
 * Provider-neutral translation request contract passed to provider adapters.
 */
export interface TranslationRequest {
  readonly requestId: string;
  readonly modelId: string;
  readonly context: ConversationContext;
  readonly systemInstruction?: string;
  readonly temperature?: number;
  readonly topP?: number;
  readonly maxTokens?: number;
  readonly stopSequences?: ReadonlyArray<string>;
  readonly responseFormat?: "text" | "json_object" | "structured_output";
  readonly tools?: ReadonlyArray<Readonly<Record<string, unknown>>>;
  readonly metadata?: Readonly<Record<string, unknown>>;
}

/**
 * Provider-neutral translation response contract returned from provider adapters.
 */
export interface TranslationResponse {
  readonly responseId: string;
  readonly requestId: string;
  readonly modelId: string;
  readonly message: AssistantMessage;
  readonly finishReason: "stop" | "length" | "tool_calls" | "content_filter" | "error";
  readonly usage: ProviderUsageStatistics;
  readonly timestamp: number;
  readonly rawResponseMetadata?: Readonly<Record<string, unknown>>;
}
