/**
 * AETHER OS — Phase 9.4 LLM Integration Layer (AI Runtime)
 * Component 4: Canonical AIResponse Envelope (`ai-response.ts`)
 *
 * @file ai-response.ts
 * @description Immutable canonical response envelope, creation factory, and invariant validation
 * for Phase 9.4 AI Runtime execution responses.
 *
 * @module @aether/ai-runtime/ai-response
 * @version 1.0.0
 * @status FROZEN SPECIFICATION COMPLIANT
 */

import {
  FinishReason,
  type CorrelationContext,
  type TokenUsage,
  type LatencyMetrics,
  type ToolCallDescriptor,
  type DiagnosticStatus,
} from "./types";
import { SystemError } from "./errors";
import { deepFreeze } from "./ai-request";

// ============================================================================
// 1. DATA CONTRACT INTERFACES
// ============================================================================

/**
 * Immutable metadata envelope attached to every runtime response.
 */
export interface AIResponseMetadata {
  /** Unique request execution identifier matching AIRequest.metadata.requestId */
  readonly requestId: string;
  /** Response creation timestamp (epoch ms) */
  readonly timestamp: number;
  /** Normalized generation finish reason across provider backends */
  readonly finishReason: FinishReason;
  /** End-to-end correlation context (sessionId, snapshotId, intentId) */
  readonly correlationContext: CorrelationContext;
}

/**
 * Canonical AIResponse Interface.
 * Emitted by Phase 9.4 and consumed by Orchestrator, Event Bus, Memory, and Downstream Systems.
 */
export interface AIResponse {
  /** Response metadata and correlation tracing */
  readonly metadata: AIResponseMetadata;
  /** Normalized completion output text generated by model */
  readonly text: string;
  /** Normalized tool invocation requests generated by model */
  readonly toolCalls: readonly ToolCallDescriptor[];
  /** Unified token consumption metrics */
  readonly usage: TokenUsage;
  /** Fine-grained request latency metrics */
  readonly latency: LatencyMetrics;
  /** Execution diagnostic status summary */
  readonly diagnostics: DiagnosticStatus;
}


// ============================================================================
// 2. FACTORY & INVARIANT VALIDATOR
// ============================================================================

/**
 * Parameters passed to the createAIResponse factory function.
 */
export interface CreateAIResponseParams {
  readonly requestId: string;
  readonly text?: string;
  readonly finishReason?: FinishReason;
  readonly toolCalls?: readonly ToolCallDescriptor[];
  readonly usage: TokenUsage;
  readonly latency: LatencyMetrics;
  readonly diagnostics: DiagnosticStatus;
  readonly correlationContext?: CorrelationContext;
}

/**
 * Factory function creating a canonical, recursively frozen AIResponse instance.
 * Validates constructor invariants and throws SystemError on fail-fast violation.
 *
 * @throws {SystemError} If any invariant or bounds check fails.
 */
export function createAIResponse(params: CreateAIResponseParams): Readonly<AIResponse> {
  // Invariant 1: Mandatory parameters check
  if (!params) {
    throw new SystemError({
      subCode: "NullResponseParams",
      message: "createAIResponse parameters object cannot be null or undefined.",
    });
  }

  // Invariant 2: Request ID validation
  if (!params.requestId || typeof params.requestId !== "string" || params.requestId.trim() === "") {
    throw new SystemError({
      subCode: "InvalidRequestId",
      message: "AIResponse requires a non-empty requestId string.",
    });
  }

  // Invariant 3: Token Usage validation
  if (!params.usage) {
    throw new SystemError({
      subCode: "MissingTokenUsage",
      message: "AIResponse requires a valid TokenUsage object.",
    });
  }
  if (
    typeof params.usage.promptTokens !== "number" ||
    params.usage.promptTokens < 0 ||
    typeof params.usage.completionTokens !== "number" ||
    params.usage.completionTokens < 0 ||
    typeof params.usage.totalTokens !== "number" ||
    params.usage.totalTokens < 0
  ) {
    throw new SystemError({
      subCode: "InvalidTokenUsageValues",
      message: "TokenUsage fields (promptTokens, completionTokens, totalTokens) must be non-negative numbers.",
    });
  }

  // Invariant 4: Latency Metrics validation
  if (!params.latency) {
    throw new SystemError({
      subCode: "MissingLatencyMetrics",
      message: "AIResponse requires a valid LatencyMetrics object.",
    });
  }
  if (
    typeof params.latency.queueDurationMs !== "number" ||
    params.latency.queueDurationMs < 0 ||
    typeof params.latency.connectionDurationMs !== "number" ||
    params.latency.connectionDurationMs < 0 ||
    typeof params.latency.timeToFirstTokenMs !== "number" ||
    params.latency.timeToFirstTokenMs < 0 ||
    typeof params.latency.totalExecutionDurationMs !== "number" ||
    params.latency.totalExecutionDurationMs < 0
  ) {
    throw new SystemError({
      subCode: "InvalidLatencyMetricsValues",
      message: "LatencyMetrics fields must be non-negative numbers.",
    });
  }

  // Invariant 5: Diagnostic Status validation
  if (!params.diagnostics) {
    throw new SystemError({
      subCode: "MissingDiagnosticStatus",
      message: "AIResponse requires a valid DiagnosticStatus object.",
    });
  }
  if (
    !params.diagnostics.providerId ||
    typeof params.diagnostics.providerId !== "string" ||
    !params.diagnostics.concreteModel ||
    typeof params.diagnostics.concreteModel !== "string"
  ) {
    throw new SystemError({
      subCode: "InvalidDiagnosticStatusValues",
      message: "DiagnosticStatus requires valid providerId and concreteModel strings.",
    });
  }

  // Invariant 6: FinishReason validation
  const finishReason = params.finishReason ?? FinishReason.STOP;
  if (!Object.values(FinishReason).includes(finishReason)) {
    throw new SystemError({
      subCode: "InvalidFinishReason",
      message: `Invalid finishReason provided: ${String(finishReason)}`,
    });
  }

  // Construct CorrelationContext defaults if omitted
  const correlationContext: CorrelationContext = {
    sessionId: params.correlationContext?.sessionId ?? "default_session",
    snapshotId: params.correlationContext?.snapshotId ?? "unknown_snapshot",
    intentId: params.correlationContext?.intentId ?? "unknown_intent",
    tenantId: params.correlationContext?.tenantId,
    traceId: params.correlationContext?.traceId,
  };

  // Construct raw internal AIResponse object
  const rawResponse: AIResponse = {
    metadata: {
      requestId: params.requestId,
      timestamp: Date.now(),
      finishReason,
      correlationContext,
    },
    text: params.text ?? "",
    toolCalls: params.toolCalls ? [...params.toolCalls] : [],
    usage: {
      promptTokens: params.usage.promptTokens,
      completionTokens: params.usage.completionTokens,
      totalTokens: params.usage.totalTokens,
      reasoningTokens: params.usage.reasoningTokens,
      cachedTokens: params.usage.cachedTokens,
    },
    latency: {
      queueDurationMs: params.latency.queueDurationMs,
      connectionDurationMs: params.latency.connectionDurationMs,
      timeToFirstTokenMs: params.latency.timeToFirstTokenMs,
      totalExecutionDurationMs: params.latency.totalExecutionDurationMs,
    },
    diagnostics: {
      providerId: params.diagnostics.providerId,
      concreteModel: params.diagnostics.concreteModel,
      attemptCount: params.diagnostics.attemptCount,
      circuitState: params.diagnostics.circuitState,
      executionResult: params.diagnostics.executionResult,
    },
  };

  // Enforce runtime deep immutability
  return deepFreeze(rawResponse);
}


// ============================================================================
// 3. SERIALIZATION HELPERS
// ============================================================================

/**
 * Returns a clean JSON representation of an AIResponse object.
 */
export function serializeAIResponse(response: AIResponse): Readonly<Record<string, unknown>> {
  if (!response) {
    throw new SystemError({
      subCode: "NullResponseSerialization",
      message: "Cannot serialize null or undefined AIResponse object.",
    });
  }

  return Object.freeze({
    requestId: response.metadata.requestId,
    timestamp: response.metadata.timestamp,
    finishReason: response.metadata.finishReason,
    text: response.text,
    toolCalls: response.toolCalls,
    usage: response.usage,
    latency: response.latency,
    diagnostics: response.diagnostics,
    correlationContext: response.metadata.correlationContext,
  });
}
